name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Check out repository
      - name: checkout repository
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'microsoft'

      # Setup and run Pakku
      - name: Download Pakku
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          gh release download \
            --repo juraj-hrivnak/Pakku \
            --pattern "*.jar"

      - name: Build modpack
        run: java -jar pakku.jar export

      # Run script to generate zip and specific changelog
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python script
        run: python .github/workflows/release.py

      # Publish release to Modrinth and GitHub
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "${{env.NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          game-versions: "${{env.MINECRAFT_VERSION}}"
          loaders: fabric
          game-version-filter: releases
          files: "build/modrinth/muffintime-mod-pack-${{env.VERSION}}.mrpack"

          # Config for Modrinth
          modrinth-id: 6s2ECxhN
          modrinth-token: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
          modrinth-changelog-file: modrinth-changelog.md
          modrinth-dependencies: vpgX4W3y(optional)

          # Config for GitHub
          github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          github-tag: "${{env.VERSION}}"
          github-changelog-file: github-changelog.md

          fail-mode: warn
